# Generated by Django 3.1.2 on 2021-05-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_list',
            name='del_status',
            field=models.BooleanField(default=True, verbose_name='Статус удаления'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_execution',
            field=models.DateField(default=None, verbose_name='Дата выполнения'),
        ),
    ]
